### ISSUE TITLE
Update error_chain to something more modern

### ISSUE THREAD

**Issue by emgre** [automatak/rodbus#12]
Quite possibly [`failure`](https://github.com/rust-lang-nursery/failure).

**Comment by jadamcrain** [comment]
As discussed, I'm just going to role the errors manually applying `std::convert::From` and std::Display` so that all errors can implement `std::error::Error` trait. This is pretty much what error chain does. We don't need the actual chaining anyway for this lib.

**Comment by jadamcrain** [comment]
completed in https://github.com/automatak/rodbus/pull/20
