### ISSUE TITLE
Decide how to host the C documentation

### ISSUE THREAD

**Issue by jadamcrain** [automatak/rodbus#19]
I recently pushed complete docs for C API. It builds nicely w/ doxygen. We can decide if we want to style it, but a biggest question is how/where to host.  We could do this on automatak.com or readthedocs.

pros/cons of Automatak:

- gets the company exposure and ups our google foo?
- need to do non-standard build automatak against this server whereas readthedocs has a simple API

**Comment by emgre** [comment]
I would suggest that we build it as a GitHub action and upload it on GitHub pages. Then point `rodbus.automatak.com` to it.

**Comment by jadamcrain** [comment]
We decided to publish all documentation into the organization's gh-pages. Rodbus could live at:

`docs.automatak.com/rodbus`

We want to also provide multi-versioning for each project docs we host there.
