### ISSUE TITLE
Flush out remaining documentation and examples

### ISSUE THREAD

**Issue by jadamcrain** [automatak/rodbus#6]

**Comment by jadamcrain** [comment]
I think the docs are now in good shape for a first release. I added a simple server example to lib.rs as well.  Requesting review from @emgre .

**Comment by emgre** [comment]
I went through all the documentation and made a few corrections in 20de981084d7537072a1093cdbd1f7c2c0f92341, looks good to me. Perhaps some more examples (e.g. an example of an implementation of `ServerHandler` right where it's defined) would be welcome, but it's ok for a first release.

Btw, if we want to write an example in the README, I found the [`doc-comment`](https://github.com/GuillaumeGomez/doc-comment) crate that can do it for use. See this [example usage](https://github.com/emgre/win-crypto-ng/blob/master/src/lib.rs#L11-L12).
